### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mpibpc-mroose** [bewersdorflab/nep-fitting#1]
Hi,
I followed your installation instructions with a fresh install of `conda` and an error stating some problems whith the downgrade of Qt. Coul you please try a fresh install and provide me a way how to get it working?

Thanks a lot!

**Comment by barentine** [comment]
Hi,
I'd be happy to help. It's an interesting error since we use wx and qt is actually marked as 'excluded' in the pyme construct.yaml file. Would you mind uploading the traceback from the failed install (including which packages it wanted to install/downgrade - it'd be nice to see which versions of pyme and nep-fitting it's pulling), as well as letting me know which OS you are running?
Thanks,
andrew

**Comment by mpibpc-mroose** [comment]
After following the advice to update the whole conda (`conda update -n base conda`) I was able to install and run the package. Maybe this is something to suggest in your installation advisory.

Greetings from Göttingen!

**Comment by barentine** [comment]
Glad to hear you're up and running! Thanks for the suggestion - I've added a note to the readme.
