### ISSUE TITLE
Plotting individual line profiles currently disabled

### ISSUE THREAD

**Issue by barentine** [bewersdorflab/nep-fitting#15]
Plotting and saving a PDF for each line profile fit individually currently lives in `nep_fitting.core.profile_fitters.ProfileFitter.plot_results`, which one cannot access through a reicpe module anymore (e.g. `nep_fitting.recipe_modules.nep_fits.FitProfiles`) because PYME's `ModuleBase` is no longer `HasTraits` but now the strict version, which means we can't assign an attribute that isn't a trait - it throws a hard error.

So, now would be a good time to refactor out the plotting. Probably the way to do this is to add an `Output` to `FitProfiles` which contains a `PYME.recipes.graphing.Plot` object, however, that would be a single plot, and now N plots for N line profiles fitted. Ideally, we would have a single recipe module output which would contain all plots to be plotted. The current hack would be to make a potentially massive subplots plot, but I think folks would find that fairly offensive/unweildy. @David-Baddeley - any thoughts on how to get around this? I'd like to resolve this before building new conda packages for nep-fitting.

**Comment by David-Baddeley** [comment]
Ouch, storing results in the recipe module itself was always counter to the envisaged spec, and could have lead to some pretty nasty problems when batch processing (recipe modules are supposed to be stateless).

I can see 2 (or potentially 3) potential ways to work around this. 

- You could have a look at `PYME.recipes.tracking.TrackFeatures` which has a `TrackManager` instance as one of it's outputs. This manages a series of (lazily instantiated) `Track` objects which encapsulate plotting for each track. A similar approach could be taken with the `NepFits`, although I'm not sure that you'd need or want the lazy instantiation.
- You could potentially subclass the one of the tabular classes and add the plotting to that. I'm not overly keen on this due to the implied contract that you can save tabular objects without loss of information.
- Some sort of generic `PlotCollection` output, although I think it might be hard to make nuanced reports using this (reports often need to know enough that it's going to be easier to use something that captures the plots and their context, rather than having the plots and context in separate generic objects).

**Comment by David-Baddeley** [comment]
Actually the simplest and fastest way would simply be to return the fitter as one of the recipe outputs (this is not that dissimilar to the tracking approach).

It's not super clean, but it's a lot better than the status quo.

**Comment by David-Baddeley** [comment]
PRed a quick and dirty fix (untested, but should work)

**Comment by barentine** [comment]
Awesome, thanks David. Just had a check - works

**Comment by barentine** [comment]
fixed with #16
